# File ui/top_sections_definitions.py

import bpy

from . import top_buttons_definitions as btn
from ..anim_offset.ui import draw_anim_offset_mask as AnimOffsetButtons


def PlaceHolderDraw(layout, context):
    layout.label(text="", icon="ERROR")


section_definitions = [
    {
        "sec_name": "Tools",
        "buttons": [
            {
                "btn_name": "Onion Skin",
                "btn_draw": btn.OnionSkinButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Anim Loop",
                "btn_draw": btn.AnimLoopButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Anim Sculpt",
                "btn_draw": btn.AnimSculptButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
            {
                "btn_name": "Anim Curves",
                "btn_draw": btn.AnimCurvesOptions,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Anim TimeWarper",
                "btn_draw": btn.AnimTimeWarper,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Anim Shift",
                "btn_draw": btn.AnimShifterButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Scrubbing",
                "btn_draw": btn.AnimScrubButton,
                "btn_enabled_graph": False,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Anim Lattice",
                "btn_draw": btn.AnimLatticeButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
            {
                "btn_name": "Anim Slice",
                "btn_draw": btn.AnimSlicerButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
            {
                "btn_name": "Anim Blast",
                "btn_draw": btn.AnimBlastButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
        ],
        "sec_enabled_graph": True,
        "sec_enabled_dope": True,
        "sec_vis_graph": True,
        "sec_vis_dope": True,
    },
    {
        "sec_name": "Toggles",
        "buttons": [
            {
                "btn_name": "Isolate Character",
                "btn_draw": btn.IsolateCharacterButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Realtime Looper",
                "btn_draw": btn.AnimRealtimeLooper,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
            {
                "btn_name": "Flex Mopaths",
                "btn_draw": btn.AnimFlexMoPathsButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Realtime Mopaths",
                "btn_draw": btn.AnimMopaths,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Silhouette",
                "btn_draw": btn.SilhouetteButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
        ],
        "sec_enabled_graph": True,
        "sec_enabled_dope": True,
        "sec_vis_graph": True,
        "sec_vis_dope": True,
    },
    {
        "sec_name": "Utils",
        "buttons": [
            {
                "btn_name": "Euler Filter",
                "btn_draw": btn.AnimEulerFilterButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Euler Gimbal",
                "btn_draw": btn.AnimEulerGimbalButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Smart Keyframes",
                "btn_draw": btn.AnimSmartKeyframesCleanupButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Markers",
                "btn_draw": btn.MarkersToolsButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Delete All Markers",
                "btn_draw": btn.MarkersDelete,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Lock/Unlock Markers",
                "btn_draw": btn.MarkersLock,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
        ],
        "sec_enabled_graph": True,
        "sec_enabled_dope": True,
        "sec_vis_graph": True,
        "sec_vis_dope": True,
    },
    {
        "sec_name": "Keyframes",
        "buttons": [
            {
                "btn_name": "Copy/Paste Pose",
                "btn_draw": btn.CopyPastePose,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
            {
                "btn_name": "AnimOffset",
                "btn_draw": AnimOffsetButtons,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Match Keyframes",
                "btn_draw": btn.MatchKeyframesButtons,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
            {
                "btn_name": "Keyframer",
                "btn_draw": btn.AnimKeyframer,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
            {
                "btn_name": "Share Keyframes",
                "btn_draw": btn.AnimShareKeyframesButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Nudge Keyframes",
                "btn_draw": btn.AnimNudgerButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "InBetweens",
                "btn_draw": btn.AnimInBetweenButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
        ],
        "sec_enabled_graph": True,
        "sec_enabled_dope": True,
        "sec_vis_graph": True,
        "sec_vis_dope": True,
    },
    {
        "sec_name": "View",
        "buttons": [
            {
                "btn_name": "Time Visualizer",
                "btn_draw": btn.TimeVisualizerButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Normalize",
                "btn_draw": btn.NormalizeGraphButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
            {
                "btn_name": "Smart Zoom",
                "btn_draw": btn.AnimSmartZoomButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Frame selected/all",
                "btn_draw": btn.AnimCurvesFrameRange,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Frame Action",
                "btn_draw": btn.AnimCurvesFrameSelectedButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Solo",
                "btn_draw": btn.AnimCurvesSoloButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
        ],
        "sec_enabled_graph": True,
        "sec_enabled_dope": True,
        "sec_vis_graph": True,
        "sec_vis_dope": True,
    },
    {
        "sec_name": "Selection",
        "buttons": [
            {
                "btn_name": "Selection Sets",
                "btn_draw": btn.AnimSelectionSets,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Select All",
                "btn_draw": btn.AnimCurvesAllButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Select Loc",
                "btn_draw": btn.AnimCurvesLocButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Select Rot",
                "btn_draw": btn.AnimCurvesRotButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Select Scale",
                "btn_draw": btn.AnimCurvesScaleButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Select CustomProps",
                "btn_draw": btn.AnimCurvesOthersButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Select ShapeKeys",
                "btn_draw": btn.AnimCurvesShapesButton,
                "btn_enabled_graph": False,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Select Constraints",
                "btn_draw": btn.AnimCurvesConstraintsButton,
                "btn_enabled_graph": False,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Show Handles",
                "btn_draw": btn.ShowHandlesButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
            {
                "btn_name": "Only Handles for Selected",
                "btn_draw": btn.OnlySelectedHandlesButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": False,
            },
        ],
        "sec_enabled_graph": True,
        "sec_enabled_dope": True,
        "sec_vis_graph": True,
        "sec_vis_dope": True,
    },
    {
        "sec_name": "Action",
        "buttons": [
            {
                "btn_name": "Graph Editor",
                "btn_draw": btn.AnimEditorGraphButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Dope Sheet",
                "btn_draw": btn.AnimEditorDopeSheetButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Action Editor",
                "btn_draw": btn.AnimEditorActionButton,
                "btn_enabled_graph": True,
                "btn_enabled_dope": True,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Shape Key Editor",
                "btn_draw": btn.AnimEditorShapeKeyButton,
                "btn_enabled_graph": False,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Grease Pencil Editor",
                "btn_draw": btn.AnimEditorGreasePencilButton,
                "btn_enabled_graph": False,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Mask Editor",
                "btn_draw": btn.AnimEditorMaskButton,
                "btn_enabled_graph": False,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "Cache File Editor",
                "btn_draw": btn.AnimEditorCacheFileButton,
                "btn_enabled_graph": False,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
            {
                "btn_name": "NLA Editor",
                "btn_draw": btn.AnimNLAButton,
                "btn_enabled_graph": False,
                "btn_enabled_dope": False,
                "btn_vis_graph": True,
                "btn_vis_dope": True,
            },
        ],
        "sec_enabled_graph": True,
        "sec_enabled_dope": True,
        "sec_vis_graph": True,
        "sec_vis_dope": True,
    }
]
